=== wso2/carbon-business-process/components/unified-endpoint/org.wso2.carbon.unifiedendpoint.core/src/main/resources/schema/uep_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 ~ Copyright (c) 2009-2010, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~      http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3.org/2005/08/addressing"
           xmlns="http://www.w3.org/2005/08/addressing"
           attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:wsdl11="http://schemas.xmlsoap.org/wsdl/"
        >


    <xs:element name="EndpointReference">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Address" type="xs:string"/>
                <xs:element ref="ReferenceParameters"/>
                <xs:element name="Metadata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="id"/>
                            <xs:element ref="wsdl11:definitions"/>
                            <xs:element ref="messageOutput"/>
                            <xs:element ref="monitoring"/>
                            <xs:element ref="errorHandling"/>
                            <xs:element ref="qos"/>
                            <xs:element ref="session"/>
                            <xs:element ref="cluster"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="transport">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" name="authorization-username" type="xs:string" />
                <xs:element minOccurs="0" maxOccurs="1" name="authorization-password" type="xs:string" />
                <xs:any minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="type" form="unqualified" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ReferenceParameters">
        <xs:complexType>
            <xs:sequence>
                <xs:any minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="id">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="uuid" type="xs:string" />
                <xs:element name="scope" type="xs:string"/>
                <xs:element name="type" type="xs:string"  />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="messageOutput">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transport">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="request-chunk" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="protocol-version" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="request-gzip" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="accept-gzip" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="connection-timeout" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="socket-timeout" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="protocol-max-redirects" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="value" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="proxy" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="host" form="unqualified" type="xs:string" />
                                    <xs:attribute name="port" form="unqualified" type="xs:string" />
                                    <xs:attribute name="domain" form="unqualified" type="xs:string" />
                                    <xs:attribute name="user" form="unqualified" type="xs:string" />
                                    <xs:attribute name="password" form="unqualified" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" form="unqualified" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="timeout">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="duration" type="xs:string" />
                            <xs:element name="action" type="xs:string"  />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="format" form="unqualified" type="xs:string" />
            <xs:attribute name="optimize" form="unqualified" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="monitoring" nillable="true">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="statistics" form="unqualified" type="xs:string" />
                    <xs:attribute name="trace" form="unqualified" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="errorHandling">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="markForSuspensionOnFailure">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="errorCodes" type="xs:string" />
                            <xs:element name="retriesBeforeSuspension" type="xs:string"  />
                            <xs:element name="retryDelay" type="xs:string"  />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="suspendOnFailure" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="errorCodes" type="xs:string"  />
                            <xs:element name="initialDuration" type="xs:string"  />
                            <xs:element name="progressionFactor" type="xs:string"  />
                            <xs:element name="maximumDuration" type="xs:string"  />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="security">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="userpwdPair" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="username" form="unqualified" type="xs:string" />
                            <xs:attribute name="password" form="unqualified" type="xs:string" />
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>

    <xs:element name="qos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enableRM" minOccurs="0">
                    <xs:complexType>
                        <xs:attribute name="policy" form="unqualified" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="enableWsSec" minOccurs="0" >
                    <xs:complexType>
                        <xs:attribute name="policy" form="unqualified" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="enableAddressing" minOccurs="0" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="1" name="ReplyTo" type="xs:anyURI" />
                        </xs:sequence>
                        <xs:attribute name="version" form="unqualified" type="xs:string" />
                        <xs:attribute name="separateListener" form="unqualified" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element ref="security"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="session">
        <xs:complexType>
            <xs:attribute name="type" form="unqualified" type="xs:string" />
        </xs:complexType>
    </xs:element>


    <xs:element name="cluster">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="membership" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:element ref="EndpointReference" maxOccurs="unbounded" />
                                <xs:element name="member" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:attribute name="url" form="unqualified" type="xs:string" />
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>

                            <xs:element name="properties" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="property">
                                            <xs:complexType>
                                                <xs:attribute name="name" form="unqualified" type="xs:string" />
                                                <xs:attribute name="value" form="unqualified" type="xs:string" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="membershipHandler" form="unqualified" type="xs:string" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="loadBalance">
                    <xs:complexType>
                        <xs:attribute name="policy" form="unqualified" type="xs:string" />
                        <xs:attribute name="algorithm" form="unqualified" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="failover" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== wso2/carbon-business-process/components/unified-endpoint/org.wso2.carbon.unifiedendpoint.core/src/main/resources/schema/unified_ep_sample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 ~ Copyright (c) 2009-2010, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~      http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
-->

<wsa:EndpointReference
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com uep_schema.xsd"
        xmlns:wsa="http://www.w3.org/2005/08/addressing"
        xmlns:wsdl11="http://schemas.xmlsoap.org/wsdl/">
    <wsa:Address>http://www.somecompany.com/my-service/svc/</wsa:Address>
    <wsa:ReferenceParameters>ANY</wsa:ReferenceParameters>
    <wsa:Metadata>
        <id>
            <name>foouniquename</name>
            <uuid>UUID</uuid>
            <scope>URI</scope>
            <type>QName</type>
        </id>

        <wsdl11:definitions>ANY</wsdl11:definitions>

	<transport type="http">                
		<Transfer-Encoding>chunked</Transfer-Encoding>                    
		<property-key>property-value</property-key>
        <authorization-username>admin</authorization-username>
        <authorization-password>admin</authorization-password>                   
	</transport>

        <messageOutput format="soap11" optimize="mtom">
            <transport type="http">
                <request-chunk value="true"/>
                <protocol-version value="1_0"/>
                <request-gzip value="true"/>
                <accept-gzip value="true"/>
                <connection-timeout value="1000"/>
                <socket-timeout value="100"/>
                <protocol-max-redirects value="2"/>
                <proxy host="http://localhost" port="9000" domain="http://localhost2" user="foo" password="pwd"/>
            </transport>

            <timeout>
                <duration>15000</duration>
                <action>discard</action>
            </timeout>
        </messageOutput>

        <monitoring statistics="enable" trace="enable">
            log_statement
        </monitoring>

        <errorHandling>
            <markForSuspensionOnFailure>
                <errorCodes>404</errorCodes>
                <retriesBeforeSuspension>100</retriesBeforeSuspension>
                <retryDelay>32</retryDelay>
            </markForSuspensionOnFailure>

            <suspendOnFailure>
                <errorCodes>607</errorCodes>
                <initialDuration>232</initialDuration>
                <progressionFactor>3</progressionFactor>
                <maximumDuration>1000</maximumDuration>
            </suspendOnFailure>
        </errorHandling>

        <qos>
            <enableRM policy="mypolicy.xml"/>
            <enableWsSec policy="secpolicy.xml"/>
            <enableAddressing version="final" separateListener="true">
                <ReplyTo>http://wso2.org/services/uepRefService</ReplyTo>
            </enableAddressing>
            <security>
                <userpwdPair username="user1" password="pwd"/>
                ANY : other security policies
            </security>
        </qos>


        <session type="http"/>

        <cluster>
            <membership membershipHandler="org.apache.synapse.core.LoadBalanceMembershipHandlerImpl">
                <!--<wsa:EndpointReference>
                </wsa:EndpointReference>-->
                <member url="http://localhost:8280/SrtProxy"/> <!--Either this or WSP EP-->
                <properties>
                    <property name="name" value="VAL"/>
                </properties>
            </membership>

            <loadBalance policy="roundRobin" algorithm="org.apache.synapse.endpoints.algorithms.LoadbalanceAlgorithmIMPL"/>
            <failover/>
        </cluster>

    </wsa:Metadata>

</wsa:EndpointReference>
